apiVersion: v1
kind: Service
metadata:
  name: {{ include "block4hw.fullname" . }}-frontapp
  labels:
    homework: frontapp
    {{- include "block4hw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    homework: frontapp
    {{- include "block4hw.selectorLabels" . | nindent 4 }}
